/* Generated By:JavaCC: Do not edit this line. grammaireSQLConstants.java */
package SGBD.AnalyseurSyntaxique;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface grammaireSQLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 5;
  /** RegularExpression Id. */
  int ORDRE = 6;
  /** RegularExpression Id. */
  int ORDERBY = 7;
  /** RegularExpression Id. */
  int NJ = 8;
  /** RegularExpression Id. */
  int JOIN = 9;
  /** RegularExpression Id. */
  int ON = 10;
  /** RegularExpression Id. */
  int valeur_verite = 11;
  /** RegularExpression Id. */
  int FROM = 12;
  /** RegularExpression Id. */
  int WHERE = 13;
  /** RegularExpression Id. */
  int AND_OR = 14;
  /** RegularExpression Id. */
  int NOT = 15;
  /** RegularExpression Id. */
  int IS = 16;
  /** RegularExpression Id. */
  int PLUS = 17;
  /** RegularExpression Id. */
  int MINUS = 18;
  /** RegularExpression Id. */
  int MULTIPLY = 19;
  /** RegularExpression Id. */
  int DIVIDE = 20;
  /** RegularExpression Id. */
  int operateur_comparaison = 21;
  /** RegularExpression Id. */
  int EXPRESSION = 22;
  /** RegularExpression Id. */
  int STRING = 23;
  /** RegularExpression Id. */
  int ATTRIBUT = 24;
  /** RegularExpression Id. */
  int LETTER = 25;
  /** RegularExpression Id. */
  int LETTER2 = 26;
  /** RegularExpression Id. */
  int CONSTANT = 27;
  /** RegularExpression Id. */
  int DIGIT = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"SELECT\"",
    "<ORDRE>",
    "\"order by\"",
    "\"NaturalJoin\"",
    "\"join\"",
    "\"on\"",
    "<valeur_verite>",
    "\"FROM\"",
    "\"WHERE\"",
    "<AND_OR>",
    "\"NOT\"",
    "\"IS\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<operateur_comparaison>",
    "<EXPRESSION>",
    "<STRING>",
    "<ATTRIBUT>",
    "<LETTER>",
    "<LETTER2>",
    "<CONSTANT>",
    "<DIGIT>",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
  };

}
